In [1]:
import numpy as np
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

print(arr.ndim)
print(arr.shape)

2
(3, 3)


In [ ]:
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

print("열 방향 평균(axis = 0) : ", arr.mean(axis=0))
print("행 방향 최댓값(axis = 1) : ", arr.max(axis=1))


열 방향 평균(axis = 0) :  [3.33333333 5.66666667 6.        ]


In [ ]:
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

print(arr.T)
print(arr.T.shape)

[[3 2 5]
 [6 4 7]
 [9 8 1]]


In [10]:
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

print(arr.flatten())
print(arr.flatten().min())

[3 6 9 2 4 8 5 7 1]
1


In [12]:
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

arr2 = arr.reshape(1,9)
print(arr2)

[[3 6 9 2 4 8 5 7 1]]


In [13]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

print(arr.dtype)
print(arr.itemsize)

float64
8


In [16]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

print(arr.sum(axis = 0))

[ 7.  9. 11. 13.]


In [17]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

print("전체 평균", arr.mean(axis = 1))

전체 평균 [3. 7.]


In [23]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

arr2 = arr.reshape(4,2)
print(arr2)

print(arr2.T.shape)

[[1.5 2.5]
 [3.5 4.5]
 [5.5 6.5]
 [7.5 8.5]]
(2, 4)


In [25]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

print(arr.flatten())
print(arr.flatten().shape)

[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]
(8,)
