In [1]:
import numpy as np
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

print(arr.ndim)
print(arr.shape)

2
(3, 3)


In [ ]:
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

print("열 방향 평균(axis = 0) : ", arr.mean(axis=0))
print("행 방향 최댓값(axis = 1) : ", arr.max(axis=1))


열 방향 평균(axis = 0) :  [3.33333333 5.66666667 6.        ]


In [ ]:
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

print(arr.T)
print(arr.T.shape)

[[3 2 5]
 [6 4 7]
 [9 8 1]]


In [10]:
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

print(arr.flatten())
print(arr.flatten().min())

[3 6 9 2 4 8 5 7 1]
1


In [12]:
arr = np.array([[3,6,9], 
                 [2,4,8],
                 [5,7,1]])

arr2 = arr.reshape(1,9)
print(arr2)

[[3 6 9 2 4 8 5 7 1]]


In [13]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

print(arr.dtype)
print(arr.itemsize)

float64
8


In [16]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

print(arr.sum(axis = 0))

[ 7.  9. 11. 13.]


In [17]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

print("전체 평균", arr.mean(axis = 1))

전체 평균 [3. 7.]


In [23]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

arr2 = arr.reshape(4,2)
print(arr2)

print(arr2.T.shape)

[[1.5 2.5]
 [3.5 4.5]
 [5.5 6.5]
 [7.5 8.5]]
(2, 4)


In [25]:
arr = np.array([[1.5, 2.5, 3.5, 4.5],
                [5.5, 6.5, 7.5, 8.5]])

print(arr.flatten())
print(arr.flatten().shape)

[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5]
(8,)


In [ ]:
# 1) np.zeros(shape)
# - 지정한 shape(모양)으로 베열을 만들고, 모든 원소를 0으로 채움
# - 주로 초기 값이 0인 배열이 필요할 때 사용 (누적합, 버퍼, 마스크) 등
# - shape은 튜플로 넣음 : (행, 열) 또는 (층, 행, 열) 등
np.zeros((3,4)) 
# 3행 4열의 2차원 배열 생성, 전부 0


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 2) np.ones(shape)
# - 지정한 shape으로 배열을 만들고, 모든 원소를 1로 채움
# - 기준 값을 1로 시작하거나, 가중치/마스의 기본값으로 자주 사용
# (2,3,4) -> 2
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
# 3) np.full(shape, full_value)
# - 지정한 shape으로 배열을 만들고, 모든 원소를 특정 값(full value)으로 채움
# - 임의의 상수로 초기화할 떄 사용
np.full((4,4),3)
# 모든 값을 3으로 채운 4*4 배열
# 4행 4열을 전부 3으로 채움

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
# 4) *_like 계열 : np.zeros_like / np.ones_like / np.full_like
# - like는 말 그대로 다른 배열을 보고 그대로 따라 만든다
# - 즉, 기본 배열의 shape을 그대로 가져외서 새 배열을 만든다.

# 장점
# - shape을 매번 직접 적을 필요가 없음(실수 줄어듦)
# - 기본적으로 dtype도 원본을 따라감(원과 같은 타입으로 안전하게 생성 가능)

arr2 = np.array([[1,2,3,4],
                 [5,6,7,8]])

np.zeros_like(arr2)
# array([[0,0,0,0],
#        [0,0,0,0]])
np.ones_like(arr2)
# array([[1,1,1,1],
#        [1,1,1,1]])
np.full_like(arr2)
# array([[1,1,1,1],
#        [1,1,1,1]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# np.random 모듈은 다양한 난수 생성 기능 제공
# 머신러닝, 시뮬레이션, 데이터 생성, 테스트 데이터 제작 등에 사용

# 1) randint(시작값, 끝값, size)
# 지정한 범의 안에서 정수형 난수 생성
# - 시작값 이상
# - 끝값 미만(끝값은 포함되지 않음)
# - size는 생성할 배열의 shape(모양)

np.random.randint(-100,100,(2,3))
# - -100이상 100미만의 정수
# - 2행 3열의 배열 생성
# - 실행할 때마다 다른 값이 나옴

# 2) seed(숫자)
# 난수 생성의 초기 상태 고정
# 같은 seed를 주면 항상 같은 난수 결과가 나옴

np.random.seed(1) # 난수 생성 기준을 1로 고정
np.random.randint(0,10,(2,3))
# seed = 1 기준으로 항상 같은 난수 배열이 생성됨

np.random.seed(2) 
np.random.randint(0,10,(2,3))
# seed = 2 기준으로 항상 같은 난수 배열이 생성됨

np.random.seed(2) 
np.random.randint(0,10,(2,2,3))
# 0 이상 10 미만 정수
# shape = (2,2,3)
# 2층, 각 층마다 2행 3열 구조의 3차원 배열 생성

array([[[8, 8, 6],
        [2, 8, 7]],

       [[2, 1, 5],
        [4, 4, 5]]], dtype=int32)

In [38]:
# 인덱싱(Indexing) : 특정 위치의 하나의 값을 가져오는 방법
# 슬라이싱(Slicing) : 일정 범의를 잘라서 여러 값을 가져오는 방법

arr1 = np.array([1,2,3,4]) # 1차원 배열,  shape = (4, )
arr2 = np.array([[1,2,3,4], # 2차원배열, shape = (2,4)
                 [5,6,7,8]])

print("파이썬 기본 리스트 예시")
Li = [1,2,3,4]
print(Li[0])

print("1차원 배열 인덱싱")
print(arr1[0])

# 기본 형태 : arr1[시작:끝:보폭]
# 시작 포함, 끝은 제외
print("1차원 배열 슬라이싱")
print(arr1[1:3:])
# 1번 인덱스부터 3번 인덱스 "전"까지
# arr[1], arr[2]

# ==2차원 배열 슬라이싱==
# 기본 형태 : arr2[행, 열]

print("2차원 배열 인덱싱")
print(arr2[0,1])
#첫 번쨰 행(0번), 두번째 열 (1번)

print(arr2[1,2])
# 두 번째 행(1번), 세 번째 열(2반)

# ==2차원 배열 슬라이싱==
# 기본형태 : arr2[행 범위, 열 범위]

print("2차원 배열의 슬라이싱")
print(arr2[1:2, 1:3])
# 행 : 1번부터 2번 직전 -> 1번 행만
# 열 : 1번부터 3번 직전 -> 1번, 2번 열

# Fancy 인덱싱 : 인덱스 번호를 리스트/배열로 여러 개 전달

print("1차원 배열 fancy 인덱싱")
print(arr1[[0,1,3]])
# 0번, 1번, 3번 인덱스를 한 번에 선택
# 결과 : [1, 2, 4]

print("2차원 배열 fancy 인덱싱")
print(arr2[[0,1], [1,3]])
# (0, 1) 위치와 (1, 2) 위치를 각각 선택
# -> arr2[0, 1] = 2
# -> arr2[1, 3] = 8
# 결과 : [2, 8]

print("fancy 인덱싱+ 슬라이싱")
print(arr2[:, [0, 3]])
# 행은 전테 선택 (:)
# 열은 0번과 3번만 선택

# 논리값 인덱싱 : True,False 조건으로 필터링

print("논리값 인덱싱")
print(arr1[[True, False, True, True]])

print(arr1[arr1 > 2])


파이썬 기본 리스트 예시
1
1차원 배열 인덱싱
1
1차원 배열 슬라이싱
[2 3]
2차원 배열 인덱싱
2
7
2차원 배열의 슬라이싱
[[6 7]]
1차원 배열 fancy 인덱싱
[1 2 4]
2차원 배열 fancy 인덱싱
[2 8]
fancy 인덱싱+ 슬라이싱
[[1 4]
 [5 8]]
논리값 인덱싱
[1 3 4]
[3 4]
