In [2]:
import numpy as np

np.array([1,2,3,4])

arr1 = np.array([1,2,3,4])
arr2 = [1,2,3,4]

print(type[arr1])

print(type[arr2])

type[array([1, 2, 3, 4])]
type[[1, 2, 3, 4]]


In [ ]:
arr2 = np.array([[1,2,3,4], 
                 [5,6,7,8]])
arr3 = np.array([[[1,2,3,4], [1,2,3,4], 
                 [1,2,3,4], [1,2,3,4]]])

print('2차원 배열')
print(arr2)
print('3차원 배열')
print(arr3)

2차원 배열
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [13]:
arr1 = np.array([1,2,3,4])

arr2 = np.array([[1,2,3,4], 
                 [5,6,7,8]])
arr3 = np.array([[[0.1,0.2,0.3,0.4], [1,2,3,4]], 
                 [[1,2,3,4], [1,2,3,4]]])

# nbim : 배열의 차원 수
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape : 배열의 형태(배열 구조를 튜플로 보여줌)
#(층 개수, 행 개수, 열 개수)
print(arr1.shape) # 숫자 4개가 있는 한줄
print(arr2.shape) # 2줄, 각 줄에 4칸
print(arr3.shape) # 2장(층), 각 장마다 2줄, 각 줄에 4칸

# size : 배열 요소의 총 개수
print(arr1.size) # 4
print(arr2.size) # 2*4=8
print(arr3.size) # 2*3*4=16

#dtype : 배열 요소의 데이터 타입
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# itemsize : 배열 원고 하나가 차지하는 메모리 크기
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

# data : 배열의 실제 데이터가 저장된 메모리 버퍼(주소)
print(arr1.data)
print(arr2.data)
print(arr3.data)

1
2
3
(4,)
(2, 4)
(2, 2, 4)
4
8
16
int64
int64
float64
8
8
8


In [ ]:
# ndarray.T : 전치 행렬(행/열을 서로 바꾸는 것)

arr = np.array([[1,2,3],
                [4,5,6]])

print('원래행렬')
print(arr)

print("전치행렬")
print(arr.T)

원래행렬
[[1 2 3]
 [4 5 6]]
전치 행렬
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# ndArray.flatten() : 1차원으로 펼치기

arr = np.array([[1,2,3],
                [4,5,6]])

print('원래행렬')
print(arr)

print('1차원으로 펼친 배열')
print(arr.flatten())

#flatten()은 복사본)copy를 만든다.
flat = arr.flatten()
flat[0] = 100

print("==배열 출력==")
print(arr)

원래행렬
[[1 2 3]
 [4 5 6]]
1차원으로 펼친 배열
[1 2 3 4 5 6]
==배열 출력==
[[1 2 3]
 [4 5 6]]


In [14]:
# ndArray.reshape() : 배열 모양 바꾸기
arr = np.array([1,2,3,4,5,6])

print("원래배열")
print(arr)

#reshape 할 땐 원본과 size가 같아야 한다.
arr2 = arr.reshape(2,3) # 2행 3열로 반환
print("reshape 배열")
print(arr2)

원래배열
[1 2 3 4 5 6]
reshape 배열
[[1 2 3]
 [4 5 6]]


In [17]:
# ndArray.sum() : 합계 구하기
# ndArray.mean() : 평균 구하기
# ndArray.max() : 최대 값 구하기
# ndArray.min() : 최소 값 구하기
# axis 옵션
# axis=0 : 열 방향 합
# axis=1:행방향 합

arr = np.array([[1,2,3],
                [4,5,6]])

print("전체합", arr.sum())
print("열 방향 합(axis=0) : ", arr.sum(axis=0))
print("행 방향 합(axis=1) : ", arr.sum(axis=1))

print("전체 평균", arr.mean())
print("열 방향 평균(axis = 0) : ", arr.mean(axis=0))
print("행 방향 평균(axis = 1) : ", arr.mean(axis=1))

print("전체 최솟값 : ", arr.min())
print("전체 최댓값 : ", arr.max())

print("열 방향 최솟값(axis = 0) : ", arr.min(axis=0))
print("열 방향 최댓값(axis = 0) : ", arr.max(axis=0))

print("행 방향 최솟값(axis = 1) : ", arr.min(axis=1))
print("행 방향 최댓값(axis = 1) : ", arr.max(axis=1))

전체합 21
열 방향 합(axis=0) :  [5 7 9]
행 방향 합(axis=1) :  [ 6 15]
전체 평균 3.5
열 방향 평균(axis = 0) :  [2.5 3.5 4.5]
행 방향 평균(axis = 1) :  [2. 5.]
전체 최솟값 :  1
전체 최댓값 :  6
열 방향 최솟값(axis = 0) :  [1 2 3]
열 방향 최댓값(axis = 0) :  [4 5 6]
행 방향 최솟값(axis = 1) :  [1 4]
행 방향 최댓값(axis = 1) :  [3 6]
