In [1]:
import numpy as np

np.array([1,2,3,4])

arr1 = np.array([1,2,3,4])
arr2 = [1,2,3,4]

print(type[arr1])

print(type[arr2])

type[array([1, 2, 3, 4])]
type[[1, 2, 3, 4]]


In [3]:
arr2 = np.array([[1,2,3,4], 
                 [5,6,7,8]])
arr3 = np.array([[1,2,3,4], [1,2,3,4], 
                 [1,2,3,4], [1,2,3,4]])

print('2차원 배열')
print(arr2)
print('3차원 배열')
print(arr3)

2차원 배열
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
